### Create a new GeoTag
POST http://localhost:3000/api/geotags
Content-Type: application/json

{
  "name": "Castle",
  "latitude": 49.01379,
  "longitude": 8.404435,
  "hashtag": "#Baum"
}

###

### Get all Geotags from the first page
GET http://localhost:3000/api/geotags?page=2&pageSize=5
###


### Get all GeoTag with query specifications
GET http://localhost:3000/api/geotags?searchTerm=Castle&latitude=49.01379&longitude=8.404435

###

### Get GeoTag by ID 
GET http://localhost:3000/api/geotags/12

###

### Update GeoTag 
PUT http://localhost:3000/api/geotags/12
Content-Type: application/json

{
  "name": "Updated Beach",
  "latitude": 36.77,
  "longitude": -119.41,
  "hashtag": "#surf"
}

###

### Get GeoTag by ID 
GET http://localhost:3000/api/geotags/12

###

### Delete GeoTag (replace with real ID)
DELETE http://localhost:3000/api/geotags/12
